### ISSUE TITLE
httpClient.SendAsync never returns anything

### ISSUE THREAD

**Issue by marnixbent** [Domysee/BittrexSharp#10]
Hi there,

I just implemented the project files into my solution. My WPF application calls the bittrex api with a valid public and private key - with all the permissions except withdraw.

When it hits line 108 of Bittrex.cs, nothing else happens. No exception, no returns. It seems like it keeps waiting for a response for ages.

What am I missing? Anyone else with this problem?

**Comment by marnixbent** [comment]
When i'm making the process synchronous:
`var jsonResponse = request(HttpMethod.Get, uri, parameters).Result;` < in GetOpenOrders()
`response = await httpClient.SendAsync(request).ConfigureAwait(false);` < in request()

Then it works..

**Comment by Domysee** [comment]
That's interesting, I never had that problem.
Could it be that there are some other threads that interfere with it?

**Comment by pcartwright81** [comment]
I found this issue too,  I run everything in a Task.Run.
IE Task.Run(() => MarketSummaryInfo = Caller.GetMarketSummary(SelectedMarket.MarketName).Result);

**Comment by Domysee** [comment]
Unfortunately this is very difficult to reproduce. If you could post a small example that has this issue you would help me tremendously.
Nonetheless, I found [a Stackoverflow answer](https://stackoverflow.com/a/10351400/3107430) that may solve the problem.
Please let me know if that is applicable to your situation.

**Comment by Domysee** [comment]
Closed due to inactivity

**Comment by sachinpachori** [comment]
I recently got confronted with this issue and .ConfigureAwait(false) worked for me. Surprisingly, the same call from other function was working without ConfigureAwait(false)
_httpRespMessage = await _httpClient.SendAsync(_httpRequest);   (this worked in another function)
 _httpRespMessage = await _httpClient.SendAsync(_httpRequest).ConfigureAwait(false) (need to use this in another function where plain httpClient.SendAsync didn't work.

**Comment by sebastianiturrioz** [comment]
> I recently got confronted with this issue and .ConfigureAwait(false) worked for me. Surprisingly, the same call from other function was working without ConfigureAwait(false)
> _httpRespMessage = await _httpClient.SendAsync(_httpRequest); (this worked in another function)
> _httpRespMessage = await _httpClient.SendAsync(_httpRequest).ConfigureAwait(false) (need to use this in another function where plain httpClient.SendAsync didn't work.

It solved my problem.
