### ISSUE TITLE
RATE_NOT_PROVIDED

### ISSUE THREAD

**Issue by marnixbent** [Domysee/BittrexSharp#11]
On my machine, decimals are noted with comma's instead of dots. Comma's get URL-encoded, that means an invalid rate value is sent to bittrex and that causes the RATE_NOT_PROVIDED error message.

Simple fix here is to replace the comma's to dots in the param values. I'll create a PR shortly.

**Comment by Domysee** [comment]
Thank you for the pull request. While it is a viable solution, and the one with the fewest changes necessary,, it would be better to use the English locale for every number to string conversion. 
That way, it is still possible to have commas in the parameters. 
I'm working on that right now, and will commit it as soon as it is finished.

**Comment by Domysee** [comment]
It should be fixed now.
If you still have that problem, please reopen the issue.

**Comment by marnixbent** [comment]
Great solution, thanks.
