### ISSUE TITLE
Exceptions when Bittrex API return false?

### ISSUE THREAD

**Issue by BrewDawg** [Domysee/BittrexSharp#14]
I realize this is a change to the API but it would be nice to have all return types inherit from BittrexResponse so we didn't have to try catch everything and do error handling in catch blocks, ie, we could just take Success? Anyway, love the API, works great.

**Comment by Domysee** [comment]
That probably will make the api easier to use, especially since it is a generic `Exception` object that is thrown, and no specialized exceptions. 
I'll do that after the other issues are fixed.

**Comment by Domysee** [comment]
This is now implemented. 
If there are any problems with that change, please create a new issue.

**Comment by BrewDawg** [comment]
Thanks, I updated to this version and all is well. It was funny, account/getbalances wasn't working until I upgraded to this one, thanx !!

**Comment by Domysee** [comment]
@BrewDawg I did a bit more than fix just this issue. 
Also tests were added for each method, which surfaced some errors that I immediately fixed ;)
