### ISSUE TITLE
Unable to open in VS 2015

### ISSUE THREAD

**Issue by wasimjee** [Domysee/BittrexSharp#16]
Hi,

unable to open in VS 2015, Shows 

`error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format. `

**Comment by Domysee** [comment]
The project format changed with VS 2017, and VS 2015 does not support the new one. So unfortunately, it will not be possible to open BittrexSharp in VS 2015.

**Comment by wasimjee** [comment]
Hi @Domysee , thanks for your reply, can you generate a dll so that we can use it in our project, or is it in nuget

**Comment by Domysee** [comment]
I will put it on nuget as soon as I have time, hopefully tomorrow.

**Comment by Domysee** [comment]
It is now on Nuget. You can install it with 

`Install-Package BittrexSharp -Version 0.1.0`
