### ISSUE TITLE
Implement a default Constructor 

### ISSUE THREAD

**Issue by Domysee** [Domysee/BittrexSharp#4]
To use the public api, api key and secret are not needed.
Therefore, it should not be necessary to provide it.
The implementation should check if a key and secret were provided, and if not, throw an exception if an api call would be made that needs them.

**Comment by ColossusFX** [comment]
`public Bittrex()
        {
            this.apiSecretBytes = encoding.GetBytes(apiSecret);
            this.httpClient = new HttpClient();
        }`

I call it with Client Class

`public class Client
    {
        public Bittrex BittrexClient { get; }

        public Client()
        {
            if (Properties.Settings.Default.Bittrex_PublicKey.Length == 0 && Properties.Settings.Default.Bittrex_PrivateKey.Length == 0)
            {
                BittrexClient = new Bittrex();
            }

            else
            BittrexClient = new Bittrex(Properties.Settings.Default.Bittrex_PublicKey, Properties.Settings.Default.Bittrex_PrivateKey);

            if (!Application.Current.Properties.Contains("BittrexClient"))
            {
                Application.Current.Properties.Add("BittrexClient", BittrexClient);
            }

            else
            {
                BittrexClient = (Bittrex)Application.Current.Properties["BittrexClient"];
            }
        }
    }`

**Comment by ColossusFX** [comment]
I call it with Client Class

`public class Client
    {
        public Bittrex BittrexClient { get; }

        public Client()
        {
            if (Properties.Settings.Default.Bittrex_PublicKey.Length == 0 && Properties.Settings.Default.Bittrex_PrivateKey.Length == 0)
            {
                BittrexClient = new Bittrex();
            }

            else
            BittrexClient = new Bittrex(Properties.Settings.Default.Bittrex_PublicKey, Properties.Settings.Default.Bittrex_PrivateKey);

            if (!Application.Current.Properties.Contains("BittrexClient"))
            {
                Application.Current.Properties.Add("BittrexClient", BittrexClient);
            }

            else
            {
                BittrexClient = (Bittrex)Application.Current.Properties["BittrexClient"];
            }
        }
    }`
