### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by jjziets** [Domysee/BittrexSharp#6]
When i try to use your code I get an exception.

I have a forum with a button that does the following.

Any ideas what could be the problem? I have tried this from my work and home network. I thought it could be the home ISP but work network gives the same issue. 

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;
using BittrexSharp;

namespace WindowsFormsApp1
{
    public partial class MainForm1 : Form
    {
        public MainForm1()
        {
            InitializeComponent();

        }

        private void button1_Click(object sender, EventArgs e)
        {
            try
            {

                var apiKey = "......"; //removed for securty
                var apiSecret = "....."; //removed for securty 
                var BittrexAPI = new Bittrex(apiKey, apiSecret);

                toolStripStatusLabel1.Text = "Balance:" + BittrexAPI.GetBalance("BTC").ToString();
            }
            catch
            {
                toolStripStatusLabel1.Text = "Diconnected to BittrexAPI";
            }
        }
    }
}

![capture](https://user-images.githubusercontent.com/19214485/29355817-c7e01f5a-8272-11e7-80ef-777f441ed61f.PNG)

**Comment by jjziets** [comment]
I have tried 3 keys. Also tried to run this the main loop.

**Comment by jjziets** [comment]
![image](https://user-images.githubusercontent.com/19214485/29356050-428aaa0e-8273-11e7-9e8a-ce6acc0a3acf.png)

**Comment by jjziets** [comment]
It sees the construct Bittrex is not called when this.httpClient = new HttpClient(); is in it. Clearly I have something set wrong in my project. My windows form is targeting DotNet 4.6.1 as that is the only one that seems to support DotNet 1.4 Standard frame work 

        public Bittrex(string apiKey, string apiSecret)
        {
            this.apiKey = apiKey;
            this.apiSecret = apiSecret;
            this.apiSecretBytes = encoding.GetBytes(apiSecret);
            // this.httpClient = new HttpClient();
        }

**Comment by Domysee** [comment]
What do you mean it is not called? Is there an exception? 

Also please keep in mind that `Bittrex` has only `async` methods, so 
```
"Balance:" + BittrexAPI.GetBalance("BTC").ToString();
```
won't work. You have to `await` the method calls, like this
```
"Balance:" + (await BittrexAPI.GetBalance("BTC").ToString());
```

**Comment by ColossusFX** [comment]
Can you help?
I keep getting this error, i havent been able to connect the client yet.

`System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'
`

**Comment by InTheta** [comment]
If you don't want an sync method/ task you can leave the await and use .Result

**Comment by Domysee** [comment]
Closed because of inactivity.
